language: "python"
matrix:
  include:
  - python: 3.10
  - python: 3.9
  - python: 3.8
  - python: 3.7
    dist: xenial
    sudo: true
  - python: pypy
install:
  - "make reqs"
script:
  - "make test"
