name: lint-test-build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint with pylint
        run: |
          python -m pylint polyline
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Build docs
        run: |
          python -m sphinx-build -b html docs docs/_build/html
